"""create table quarto

Revision ID: 064b9edc8cdd
Revises: e53b17c721ac
Create Date: 2025-11-06 21:00:55.256079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064b9edc8cdd'
down_revision: Union[str, Sequence[str], None] = 'e53b17c721ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quartos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('republica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['republica_id'], ['republicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', 'republica_id')
    )
    op.add_column('membros', sa.Column('quarto_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'membros', 'quartos', ['quarto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'membros', type_='foreignkey')
    op.drop_column('membros', 'quarto_id')
    op.drop_table('quartos')
    # ### end Alembic commands ###
