"""update table republica

Revision ID: e53b17c721ac
Revises: 6d69eea999b8
Create Date: 2025-11-06 14:29:23.634118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53b17c721ac'
down_revision: Union[str, Sequence[str], None] = '6d69eea999b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('republicas', sa.Column('nome', sa.String(), nullable=False))
    op.add_column('republicas', sa.Column('cep', sa.String(), nullable=False))
    op.add_column('republicas', sa.Column('rua', sa.String(), nullable=False))
    op.add_column('republicas', sa.Column('numero', sa.String(), nullable=False))
    op.add_column('republicas', sa.Column('bairro', sa.String(), nullable=False))
    op.add_column('republicas', sa.Column('cidade', sa.String(), nullable=False))
    op.add_column('republicas', sa.Column('estado', sa.String(), nullable=False))
    op.add_column('republicas', sa.Column('complemento', sa.String(), nullable=True))
    op.drop_column('republicas', 'name')
    op.drop_column('republicas', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('republicas', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('republicas', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('republicas', 'complemento')
    op.drop_column('republicas', 'estado')
    op.drop_column('republicas', 'cidade')
    op.drop_column('republicas', 'bairro')
    op.drop_column('republicas', 'numero')
    op.drop_column('republicas', 'rua')
    op.drop_column('republicas', 'cep')
    op.drop_column('republicas', 'nome')
    # ### end Alembic commands ###
